//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labo.Common.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Labo.Common.Data.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current SessionScope is already completed. You should dispose the SessionScope.
        /// </summary>
        internal static string Current_SessionScope_is_already_completed {
            get {
                return ResourceManager.GetString("Current_SessionScope_is_already_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to totalItemsCount cannot be smaller than 0.
        /// </summary>
        internal static string PagedResult_totalItemsCount_cannot_be_smaller_than_0 {
            get {
                return ResourceManager.GetString("PagedResult_totalItemsCount_cannot_be_smaller_than_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to totalPages cannot be smaller than 0.
        /// </summary>
        internal static string PagedResult_totalPages_cannot_be_smaller_than_0 {
            get {
                return ResourceManager.GetString("PagedResult_totalPages_cannot_be_smaller_than_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pageNo must be greater than 0.
        /// </summary>
        internal static string PageNo_must_be_greater_than_0 {
            get {
                return ResourceManager.GetString("PageNo_must_be_greater_than_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pageSize must be greater than 0.
        /// </summary>
        internal static string PageSize_must_be_greater_than_0 {
            get {
                return ResourceManager.GetString("PageSize_must_be_greater_than_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to session has aborted.
        /// </summary>
        internal static string SessionScope_Session_has_aborted {
            get {
                return ResourceManager.GetString("SessionScope_Session_has_aborted", resourceCulture);
            }
        }
    }
}
