//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1573
namespace Labo.Common.Data.SqlServer.Tests.Data
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EfRepositoryDbEntities : DbContext
    {
        static EfRepositoryDbEntities()
    	{ 
    		Database.SetInitializer<EfRepositoryDbEntities>(null);
    	}
    	
    	public EfRepositoryDbEntities() : base("name=EfRepositoryDbEntities")
        {
        }
    	
    	public EfRepositoryDbEntities(string nameOrConnectionString) : base(nameOrConnectionString)
    	{	
    	}
    
    	public EfRepositoryDbEntities(string nameOrConnectionString, DbCompiledModel model) : base(nameOrConnectionString, model)
    	{
    	}
    
    	public EfRepositoryDbEntities(DbConnection existingConnection, bool contextOwnsConnection) : base(existingConnection, contextOwnsConnection)
    	{
    	}
    
    	public EfRepositoryDbEntities(DbConnection existingConnection, DbCompiledModel model, bool contextOwnsConnection) : base(existingConnection, model, contextOwnsConnection)
    	{
    	}
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {		
    		modelBuilder.Configurations.Add(new Customer_Mapping());
    		modelBuilder.Configurations.Add(new Order_Mapping());
    		modelBuilder.Configurations.Add(new OrderItem_Mapping());
    		modelBuilder.Configurations.Add(new Product_Mapping());
        }
    	
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderItem> OrderItems { get; set; }
        public DbSet<Product> Products { get; set; }
    }
}
