//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labo.Common.Data.SqlServer.Tests.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class OrderItem_Mapping : EntityTypeConfiguration<OrderItem>
    {
        public OrderItem_Mapping()
        {                        
              this.HasKey(t => new {t.OrderId, t.ProductId, t.Quantity});        
              this.ToTable("OrderItem");
              this.Property(t => t.OrderId).HasColumnName("OrderId").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.None));
              this.Property(t => t.ProductId).HasColumnName("ProductId").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.None));
              this.Property(t => t.Quantity).HasColumnName("Quantity").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.None));
              this.HasRequired(t => t.Order).WithMany(t => t.OrderItems).HasForeignKey(d => d.OrderId);
              this.HasRequired(t => t.Product).WithMany(t => t.OrderItems).HasForeignKey(d => d.ProductId);
         }
    }
}
