//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1573
namespace Labo.Common.Data.Tests.EntityFramework.Contexts.ModelFirst
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelFirstModelContainer : DbContext
    {
        static ModelFirstModelContainer()
    	{ 
    		Database.SetInitializer<ModelFirstModelContainer>(null);
    	}
    	
    	public ModelFirstModelContainer() : base("name=ModelFirstModelContainer")
        {
        }
    	
    	public ModelFirstModelContainer(string nameOrConnectionString) : base(nameOrConnectionString)
    	{	
    	}
    
    	public ModelFirstModelContainer(string nameOrConnectionString, DbCompiledModel model) : base(nameOrConnectionString, model)
    	{
    	}
    
    	public ModelFirstModelContainer(DbConnection existingConnection, bool contextOwnsConnection) : base(existingConnection, contextOwnsConnection)
    	{
    	}
    
    	public ModelFirstModelContainer(DbConnection existingConnection, DbCompiledModel model, bool contextOwnsConnection) : base(existingConnection, model, contextOwnsConnection)
    	{
    	}
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {		
    		modelBuilder.Configurations.Add(new CustomerModel_Mapping());
        }
    	
        public DbSet<CustomerModel> CustomerModelSet { get; set; }
    }
}
